Repository alan-turing-institute/binderhub-deploy, pull requests merged in 2019-06, with the labels that each got.

#22 Bugfixes and added output for deployment
  Dockerfile
  README.md
  azure/paas/arm/azure.deploy.json
  create_config.py
  deploy.sh
  images/az_account_list.png
  images/create-for-rbac.png
  images/create_sp.png
  setup.sh
  template-config.json
Labels: bug

#36 [Ready for Review] Add auto-upgrade script for helm chart
  README.md
  upgrade.sh
Labels: enhancement

#41 [Ready for Review] Edit teardown.sh to manipulate kube config file
  README.md
  info.sh
  logs.sh
  teardown.sh
Labels: enhancement

#43 [Ready for Review] Fixing creation of config.yaml and secret.yaml
  .gitignore
  README.md
  config-template.yaml
  create_config.py
  create_secret.py
  deploy.sh
  secret-template.yaml
  setup.sh
Labels: bug

#51 [Ready for Review] Fix parsing of docker ID to config.yaml
  azure/paas/arm/azure.deploy.json
  deploy.sh
  info.sh
  logs.sh
  teardown.sh
  upgrade.sh
Labels: bug

#30 [Ready for Review] Restructure README
  README.md
  images/blob_storage.png
  images/container_events.png
  images/container_logs.png
  images/select_blob_storage.png
  images/select_container_instance.png
  images/select_resource_group.png
  images/storage_account.png
Labels: documentation

#52 Update ARM template to give choice of Docker images
  .gitignore
  azure/paas/arm/azure.deploy.json
Labels: enhancement
